gin:
  ip: 0.0.0.0
  port: 8888

mysql:
  user: root
  password: 123114
  host: 127.0.0.1
  port: 3306
  db_name: sales_system
  prefix: ss_

translator:
  locale: zh

log:
  file_path: ./log/sales_system.log
  max_size: 5
  max_backups: 10
  max_age: 365
  compress: true

allow_origin:
  origins:
    - "http://localhost:5137"
    - "http://localhost:3000"
    - "http://127.0.0.1:5137"
    - "http://127.0.0.1:3000"